version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Instalando dependencias para validar"
      - pip install -r blacklist/src/requirements.txt
      - pip install coverage

  build:
    commands:
      - echo "Seteando PYTHONPATH"
      - export PYTHONPATH="${PYTHONPATH}:$(pwd)/blacklist/src"
      
      - echo "Ejecutando pruebas con unittest"
      - coverage run -m unittest discover -s blacklist/src/tests
      - coverage report --fail-under=100
      
      - echo "Empaquetando solo archivos dentro de src"
      - cd blacklist/src
      - zip -r ../app.zip . -x "*.git*" "*__pycache__*" "*.pyc" "*.pyo" "*.dist-info*" "*.egg-info*" ".venv*" "package*" "venv*" "build*" "*.log"

artifacts:
  files:
    - app.zip
  base-directory: blacklist
