version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Instalando dependencias para validar"
      - pip install -r blacklist/src/requirements.txt
      - pip install pytest


  build:
    commands:
      - echo "Seteando PYTHONPATH"
      - export PYTHONPATH="${PYTHONPATH}:$(pwd)/blacklist/src"
      
      - echo "Ejecutando pruebas con pytest"
      - pytest blacklist/src/tests --maxfail=1 --disable-warnings --tb=short
      
      - echo "Empaquetando solo archivos del repositorio"
      - zip -r app.zip . -x "*.git*" "*__pycache__*" "*.pyc" "*.pyo" "*.dist-info*" "*.egg-info*" ".venv*" "package*" "venv*" "build*" "*.log"
artifacts:
  files:
    - app.zip
